<?php

/**
 * Implementation of hook_menu().
 */
function reg_dest_menu() {
  $items = array();
  
  $items['thank-you'] = array(
    'title' => 'Thank You for Registering', 
    'page callback' => 'reg_dest_pagecontent', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function reg_dest_pagecontent() {
  return t('Thank you for Registering');
}

/**
 * Implementation of hook_form_alter().
 */
function reg_dest_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_register':
        $form['#redirect'] = 'thank-you';
      break;
  }
}